server:
  port: 8888
spring:
  profiles:
    active: vault,git
  cloud:
    config:
      server:
        git:
          uri: # set on deployment via ENV
          cloneOnStart: false
          ignore-local-ssh-settings: true
          passphrase: ${SSH_PASSPHRASE}
          private-key: ${SSH_KEY}
          order: 1
        vault:
          host: # set on deployment via ENV
          port: 443
          skip-ssl-validation: true
          scheme: https
          order: 0
          backend: config-server
          profile-separator: '-'
          kv-version: 2

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        #        curl -i -X POST -H 'Content-Type: application/json' -d '{"configuredLevel": "INFO"}' http://localhost:8888/actuator/loggers/ROOT
        include: health, env, metrics, threaddump, heapdump, info, configprops, prometheus, loggers
    loggers:
      enabled: true
