name: Gradle Release

on: workflow_dispatch

jobs:
  release:
    uses: octopusden/octopus-base/.github/workflows/common-java-gradle-release.yml@gradle-templates
    with:
      java-version: "11"
      docker-image: config-service
      flow-type: public
    secrets: inherit
