name: Gradle Release

on: workflow_dispatch

jobs:
  release:
    uses: octopusden/octopus-base/.github/workflows/common-java-gradle-release.yml@v2.1.7
    with:
      flow-type: public
      java-version: '11'
      docker-image: config-server
    secrets: inherit
